game/urls.py
from django.urls import path
from .views import CreateGameView
from django.contrib.auth.views import LogoutView

app_name = 'game'

urlpatterns = [
    path('', CreateGameView.as_view(), name='create'),
]

nonogram/urls.py
from django.contrib import admin
from django.urls import path, include
from nonogram.settings import DEBUG
from .views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', HomePageView.as_view(), name='home'),
    path('accounts/', include('user.urls', namespace='user')),
    path('game/', include('game.urls', namespace='game')),
]

if DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

user/urls.py
from django.urls import path
from .views import RegisterUserView, ResetPasswordView, ChangePasswordView, LoginView
from django.contrib.auth.views import LogoutView

app_name = 'user'

urlpatterns = [
    path('signup/', RegisterUserView.as_view(), name='signup'),
    path('password/reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password/change/', ChangePasswordView.as_view(), name='password_change'),
    path('login/', LoginView.as_view(), name="login", kwargs={'next_page': '/'}),
    path('logout/', LogoutView.as_view(), name='logout'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap5 %}
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"
        integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"
        integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.7.1/dist/chart.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
        <title>{% block title %} {% endblock %}</title>
    <link rel="icon" href="{% static 'user/img/logo.png' %}" type="image/x-icon">
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
        }

        * {
            box-sizing: border-box;
        }

        .topnav {
            overflow: hidden;
            background-color: #333;
        }

        .topnav a {
            float: left;
            display: block;
            color: #f2f2f2;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
        }

        .topnav a:hover {
            background-color: #ddd;
            color: black;
        }

        .topnav a.active {
            background-color: #04AA6D;
            color: white;
        }

        .topnav .icon {
            display: none;
        }

        @media screen and (max-width: 600px) {
            .topnav a:not(:first-child) {
                display: none;
            }

            .topnav a.icon {
                float: right;
                display: block;
            }
        }

        @media screen and (max-width: 600px) {
            .topnav.responsive {
                position: relative;
            }

            .topnav.responsive .icon {
                position: absolute;
                right: 0;
                top: 0;
            }

            .topnav.responsive a {
                float: none;
                display: block;
                text-align: left;
            }
        }
    </style>
    {% block style %}

    {% endblock %}
</head>

<body>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert"
        style="margin-left:5%; margin-right:5%">
        {{ message }}
        <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    <div class="topnav" id="myTopnav">
        <a href="/" class="active">Home</a>
        {% if user.is_superuser %}
        <a href="/admin">Admin</a>
        {% endif %}
        {% if user.is_authenticated %}
        <a href="{% url 'user:password_change' %}">Change Password</a>

        <form method="POST" action="{% url 'user:logout' %}">
        {% csrf_token %}
            <a type="submit" onclick="this.parentNode.submit()" href="#">Log Out</a>
        </form>

        {% else %}
        <a href="{% url 'user:password_reset' %}">Reset Password</a>
        <a class="nav navbar-right" href="{% url 'user:login' %}"><span class="glyphicon glyphicon-user">Login</span></a>
        <a class="nav navbar-right" href="{% url 'user:signup' %}"><span class="glyphicon glyphicon-user">SignUp</span></a>
        {% endif %}
        <a href="javascript:void(0);" class="icon" onclick="myFunction()">
            <i class="fa fa-bars"></i>
        </a>
    </div>
    <br>
    <br>
    <br>
    <div class="content container">
        {% block content %}

        {% endblock %}
    </div>
    <script>
        function myFunction() {
            var x = document.getElementById("myTopnav");
            if (x.className === "topnav") {
                x.className += " responsive";
            } else {
                x.className = "topnav";
            }
        }
    </script>
    {% block script %}
    {% endblock %}
</body>

</html>

templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<h2>Home Page</h2>
{% endblock %}